FROM ubuntu:latest

RUN apt-get update && \
    apt-get -qy full-upgrade && \
    apt-get install -qy curl python3 python-is-python3 python3-pip && \
    curl -sSL https://get.docker.com/ | sh
RUN python -m pip config set global.break-system-packages true
RUN pip install wandb[launch]

WORKDIR /home

COPY launch.sh launch.sh

ENTRYPOINT ["./launch.sh", "-l"]
