# docker-compose run ttex bash

services:

  ttex:
    container_name: ttex
    env_file: .env
    image: taisrc/ttex${VER:+:}${VER}
    build:
        context: ..
        dockerfile: docker/Dockerfile
    volumes:
      - ../ttex:/ttex
      - ../tests:/tests
      
  wandb_launcher:
    container_name: wandb_launcher
    env_file: .env
    image: taisrc/wandb:launcher${VER:+-}${VER}
    privileged: true
    build:
        context: ..
        dockerfile: docker/Dockerfile_launcher
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      
  wandb_job:
    container_name: wandb_job
    env_file: .env
    depends_on:
     - ttex
    image: taisrc/wandb:job${VER:+-}${VER}
    build:
        context: ..
        no_cache: true
        dockerfile: docker/Dockerfile_job
    volumes:
      - ../ttex:/ttex
      - ../tests:/tests
    entrypoint: bash
