name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - "**.md"
      - "docker/**"
  workflow_dispatch: # allow triggering workflow manually
    inputs:
      reason:
        description: "Reason for Running"
        required: false
        default: "Manually trigger ci"

jobs:
  release-build:
    uses: TAI-src/.github/.github/workflows/release-python.yml@main
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      contents: read
    with:
      pkg-src: .
    secrets: inherit

  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - release-build

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: release
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      # url: https://pypi.org/p/YOURPROJECT

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: ./dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
