name: Testing and Linting

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - "**.md"
      - "docker/**"
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - "**.md"
      - "docker/**"
  workflow_dispatch: # allow triggering workflow manually
    inputs:
      reason:
        description: "Reason for Running"
        required: false
        default: "Manually trigger ci"

jobs:
  example:
    runs-on: ubuntu-latest
    if: github.triggering_actor != 'github-actions[bot]' && github.triggering_actor != 'auto-cid'
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/checkout@v4
        with:
          # This is necessary so that we have the tags.
          fetch-depth: 0
          token: ${{ secrets.CID_PAT }}
      - uses: mtkennerly/dunamai-action@v1
        with:
          env-var: MY_VERSION
          args: --style semver
      - run: echo $MY_VERSION
      - run: sed -i '/__version__ = /s/.*/__version__ = "'${MY_VERSION}'"/' setup.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Version Push
